-- Run this once in your Supabase project's SQL Editor.

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_slug text not null
    check (char_length(post_slug) between 1 and 100),
  author_name text not null
    check (char_length(btrim(author_name)) between 2 and 60),
  body text not null
    check (char_length(btrim(body)) between 2 and 1000),
  approved boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists comments_public_feed_idx
  on public.comments (post_slug, created_at desc)
  where approved = true;

alter table public.comments enable row level security;

revoke all on table public.comments from anon;
grant select (id, post_slug, author_name, body, created_at)
  on table public.comments to anon;
grant insert (post_slug, author_name, body)
  on table public.comments to anon;
grant usage, select on sequence public.comments_id_seq to anon;

drop policy if exists "Approved comments are public" on public.comments;
create policy "Approved comments are public"
  on public.comments
  for select
  to anon
  using (approved = true);

drop policy if exists "Visitors can submit comments for moderation" on public.comments;
create policy "Visitors can submit comments for moderation"
  on public.comments
  for insert
  to anon
  with check (
    approved = false
    and post_slug ~ '^[a-z0-9-]+$'
    and char_length(btrim(author_name)) between 2 and 60
    and char_length(btrim(body)) between 2 and 1000
  );

comment on table public.comments is
  'Moderated public comments for Flyness Namatama Systems Notes.';
