-- Run this once in your Supabase project's SQL Editor.

create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  email text not null
    check (
      char_length(btrim(email)) between 5 and 254
      and email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'
    ),
  name text
    check (name is null or char_length(btrim(name)) between 1 and 80),
  source text not null default 'website'
    check (source in ('website')),
  subscribed_at timestamptz not null default now()
);

create unique index if not exists subscribers_email_unique_idx
  on public.subscribers (lower(email));

create index if not exists subscribers_recent_idx
  on public.subscribers (subscribed_at desc);

alter table public.subscribers enable row level security;

revoke all on table public.subscribers from anon;
grant insert (email, name, source)
  on table public.subscribers to anon;
grant usage, select on sequence public.subscribers_id_seq to anon;

drop policy if exists "Visitors can subscribe by email" on public.subscribers;
create policy "Visitors can subscribe by email"
  on public.subscribers
  for insert
  to anon
  with check (
    source = 'website'
    and char_length(btrim(email)) between 5 and 254
    and email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'
    and (name is null or char_length(btrim(name)) between 1 and 80)
  );

comment on table public.subscribers is
  'Private newsletter subscriber list for Flyness Namatama Systems Notes.';
