-- Run this once in your Supabase project's SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  email text not null
    check (
      char_length(btrim(email)) between 5 and 254
      and email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'
    ),
  name text not null
    check (char_length(btrim(name)) between 1 and 80),
  source text not null default 'website'
    check (source in ('website')),
  unsubscribe_token uuid not null default gen_random_uuid(),
  unsubscribed_at timestamptz,
  subscribed_at timestamptz not null default now()
);

alter table public.subscribers
  add column if not exists unsubscribe_token uuid not null default gen_random_uuid();

alter table public.subscribers
  add column if not exists unsubscribed_at timestamptz;

alter table public.subscribers
  add column if not exists subscribed_at timestamptz not null default now();

update public.subscribers
set name = 'Subscriber'
where name is null or char_length(btrim(name)) = 0;

alter table public.subscribers
  alter column name set not null;

create unique index if not exists subscribers_email_unique_idx
  on public.subscribers (lower(email));

create index if not exists subscribers_recent_idx
  on public.subscribers (subscribed_at desc);

create unique index if not exists subscribers_unsubscribe_token_unique_idx
  on public.subscribers (unsubscribe_token);

alter table public.subscribers enable row level security;

revoke all on table public.subscribers from anon;
grant insert (email, name, source)
  on table public.subscribers to anon;
grant usage, select on sequence public.subscribers_id_seq to anon;

drop policy if exists "Visitors can subscribe by email" on public.subscribers;
create policy "Visitors can subscribe by email"
  on public.subscribers
  for insert
  to anon
  with check (
    source = 'website'
    and char_length(btrim(email)) between 5 and 254
    and email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'
    and char_length(btrim(name)) between 1 and 80
  );

comment on table public.subscribers is
  'Private newsletter subscriber list for Flyness Namatama Systems Notes.';

create table if not exists public.sent_post_alerts (
  id bigint generated by default as identity primary key,
  post_guid text not null unique,
  post_title text not null,
  sent_at timestamptz not null default now()
);

alter table public.sent_post_alerts enable row level security;

revoke all on table public.sent_post_alerts from anon;

insert into public.sent_post_alerts (post_guid, post_title)
values (
  'https://flynessnamatama.com/#/writing/hidden-human',
  'The Hidden Human in System Design: Why is it still so hard to write safe parallel code?'
)
on conflict (post_guid) do nothing;

comment on table public.sent_post_alerts is
  'Tracks which RSS posts have already triggered subscriber email alerts.';
